### ISSUE TITLE
🎁: WO Notification sidesheet

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#1139] opened 2024-10-02 11:19 UTC
## Expected outcome
Add a notification tab similar to Handover in sidesheet. only using the WO connection. All data should be in FAM

**Comment by ken-mellem** [comment] 2024-10-08 08:01
I believe this is a duplicate of 
- https://github.com/equinor/cc-components/issues/384

**Comment by ken-mellem** [comment] 2024-10-08 08:02
Duplicate of #384

**Closed** 2024-10-08 08:03 UTC
Labels: duplicate, feature
