### ISSUE TITLE
🐛: Handover: MC status showing OK on empty packages

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#936] opened 2024-04-10 09:47 UTC
## Description
Packages without checklists gets OK status, should be OS.

## Reproduce
Open a package with no mc scope. It will show MC status as "OK"
![Image](https://github.com/equinor/cc-components/assets/11732817/8470ee49-2e43-422b-9ed5-2a29ee3ddaee)

## Expected behavior
Expect MC status to be "OS" like in old Fusion version + ProCoSys:
![Image](https://github.com/equinor/cc-components/assets/11732817/a8df2335-2224-4abd-8f94-070cdc0387a1)

**Comment by EdwardBrunton** [comment] 2024-04-23 08:52
When getting the data from FAM the Custom_CommissioningPackageV3 model contains the wrong status

**Comment by Gustav-Eikaas** [comment] 2024-05-02 08:40
@aman-riaz Is this something we calculate in the view?

**Comment by aman-riaz** [comment] 2024-05-02 10:55
The condition in the view did not take in account commpkg with mc scope = null. A condition for this have now been added. 
Please verify when you recieve the changes on your end @EdwardBrunton

**Comment by MagnusGjosund** [comment] 2024-05-13 14:17
I have checked a lot of handovers with mc status OK in PP. Can't fint any that has Outstanding in ProCoSys. Seems like the problem is fixed. I will close the issue

**Closed by MagnusGjosund** 2024-05-13 14:17 UTC
Labels: bug, data
