### ISSUE TITLE
:bug: Loop: mcContent status is missing on some loops

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#598] opened 2023-09-26 05:53 UTC
## Describe the bug
Some loops has empty mcContentStatus both on screen and in Excel report.
I guess this is because some loops has tags with register type "Function" wich will never have a mcStatus or commPk/mcPk.
( Tags with register Function or signal is software functions/not physical equipment )

To fix this we can do one of two things when calculating the worst status:
1) Do not take into account tags with register "Function" and "Signal"
2) Do not take into account tags with empty commPk

Because of this calculation, also the actual mcContent complete is empty .

## Reproduce
Open Loop 24-0026 and see that it has empty mcContentStatus

## Business Value / Developer Experience
The person hired as loop-coordinator at Johan Castberg need correct data to prioritize correctly

## Screenshots
The tags inside the drawn squareBrackets is function-tags
![image](https://github.com/equinor/lighthouse/assets/11732817/d8281c35-3b1d-4991-a52e-b659beb872b8)

## User Acceptance Tests (UAT)

> How to test

- [x] Loop 24-0026 should have OK mcContentStatus
- [x] MC status should be shown in checklist table, similar to JC portal.

**Comment by AreWiv** [comment] 2023-09-26 07:25
@atlewee Extensive and very good description!

**Comment by Gustav-Eikaas** [comment] 2023-09-27 09:55
1/2 fixed

Loop 24-0026 should have OK mcContentStatus
fixed by changing calculation in fam to exclude register types "function" | "signal"

**Comment by BenSvend** [comment] 2023-09-27 11:03
MC status should now be visible. I've added the changes to test. Can you and verify  @AreWiv ?

https://webserver-fusion-project-portal-test.radix.equinor.com/apps/loop/94dd5f4d-17f1-4312-bf75-ad75f4d9572c?tab=grid&item=ed187f3b-28c2-c84b-e053-2810000a69dd

![image](https://github.com/equinor/cc-components/assets/133334563/90cb09a5-3b88-4494-881d-19dd113073ef)

**Comment by BenSvend** [comment] 2023-09-27 13:13
@atlewee Changes have now been pushed to production. FAM have also pushed the logic changes of calculating the worst status. So it works as intended now.

**Comment by Gustav-Eikaas** [comment] 2023-09-28 09:51
@atlewee can this be closed now?

**Comment by atlewee** [comment] 2023-09-28 11:53
Yup! looks perfect now :)

**Closed** 2023-09-29 07:46 UTC
Labels: bug, QA/UAT
